[window]
padding.x = 4
padding.y = 4

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 12.0

[general]
import = [
    "~/.config/alacritty/theme.toml"
]

