[colors.bright]
black = "#484f58"
blue = "#79c0ff"
cyan = "#56d4dd"
green = "#56d364"
magenta = "#d2a8ff"
red = "#ff7b72"
white = "#f0f6fc"
yellow = "#e3b341"

[colors.normal]
black = "#484f58"
blue = "#58a6ff"
cyan = "#39c5cf"
green = "#3fb950"
magenta = "#bc8cff"
red = "#f85149"
white = "#c9d1d9"
yellow = "#d29922"

[colors.primary]
background = "#0d1117"
foreground = "#c9d1d9"
