#!/usr/bin/env sh

empty=""
quarter=""
half=""
three_quarter=""
full=""

cap=$(cat /sys/class/power_supply/BAT0/capacity)

if [[ $cap -ge 80 ]]; then
  echo "$full $cap%"
elif [[ $cap -ge 50 ]]; then
  echo "$three_quarter $cap%"
elif [[ $cap -ge 40 ]]; then
  echo "$half $cap%"
elif [[ $cap -ge 20 ]]; then
  echo "$quarter $cap%"
elif [[ $cap -ge 0 ]]; then
  echo "$empty $cap%"
fi
