---

username: eagle7
configs_repo: "{{ home_dir }}/code/configs"
git_full_name: "Aditya Azad"
git_email: "adityaazad121@gmail.com"

programs:
  - compilers
  - mise_runtimes
  - net_tools
  - chrony
  - zellij
  - ripgrep
  - python_lsp
  - neovim
  - fontconfig
  - singularity
  - realsense
  - nvidia_container_toolkit
  - nvliblist
  - local_scripts
  - bashrc_common
  - bashrc_jetson
  - pi

ros_domain_id: 7
