---

username: azada
configs_repo: "{{ playbook_dir | dirname | dirname }}"
git_full_name: "Aditya Azad"
git_email: "adityaazad121@gmail.com"

programs:
  - uninstall
  - upgrade
  - laptop_base
  - compilers
  - mise_runtimes
  - net_tools
  - chrony
  - zellij
  - heif
  - krita
  - keepass2
  - xournalpp
  - calibre
  - ripgrep
  - brave
  - nvidia_driver
  - latex
  - nvtop
  - texlab
  - neovim
  - kitty
  - docker
  - syncthing
  - freefilesync
  - steam
  - discord
  - fontconfig
  - noctalia_repo
  - umbriel
  - noctalia
  - noctalia_greeter
  - refree
  - local_scripts
  - vfio
  - bashrc_common
  - bashrc_desktop
  - setup_hosts
  - bizon
  - pi

ros_domain_id: 0

nvidia_driver_version: 580
px4_path: "{{ home_dir }}/code/PX4-Autopilot"
