---

home_dir: "{{ '/home/' + username }}"

configs_repo: "{{ home_dir }}/code/configs"

code_dir: "{{ home_dir }}/code"

software_dir: "{{ home_dir }}/.software"

bashrc_file: "{{ home_dir }}/.bashrc"

mise_bin: "{{ home_dir }}/.local/bin/mise"

cargo_env: "{{ home_dir }}/.cargo/env"
cargo_bin: "{{ home_dir }}/.cargo/bin"
