/* generated by st from themes/<name>/colors.conf — palette accent for GTK3 apps */
@define-color theme_selected_bg_color {{COLOR4}};
@define-color theme_selected_fg_color {{FG}};
@define-color accent_color {{COLOR4}};
@define-color accent_bg_color {{COLOR4}};
@define-color accent_fg_color {{FG}};
