---

- name: Add graphics-drivers PPA
  community.general.apt_repository:
    repo: ppa:graphics-drivers/ppa
    state: present
    update_cache: true

- name: Install nvidia-driver-{{ nvidia_driver_version | default(580) }}
  ansible.builtin.apt:
    name: "nvidia-driver-{{ nvidia_driver_version | default(580) }}"
    state: present
