---

- name: Install PyTorch (default wheels) for jetson aarch64
  ansible.builtin.pip:
    name:
      - torch
      - torchvision
    extra_args: "--index-url https://download.pytorch.org/whl/cu126"
    state: present
  become: false
  when: ansible_architecture == "aarch64"
