---

- name: Link refree config
  ansible.builtin.file:
    src: "{{ configs_repo }}/refree"
    dest: "{{ home_dir }}/.refree"
    state: link
    force: true
  become: true
  become_user: "{{ username }}"
