---

- name: Install ripgrep via cargo
  ansible.builtin.shell: |
    set -e
    {{ cargo_bin }}/cargo install ripgrep
  args:
    executable: /bin/bash
    creates: "{{ cargo_bin }}/rg"
  become: true
  become_user: "{{ username }}"
