---

- name: Remove bloat
  ansible.builtin.apt:
    name:
      - apport
      - apport-symptoms
      - whoopsie
      - whoopsie-preferences
      - ubuntu-report
      - ubuntu-pro-client
      - landscape-client
      - popularity-contest
      - motd-news-config
    state: absent
    purge: true
  failed_when: false

- name: Clean up now-unused dependencies (final autoremove)
  ansible.builtin.apt:
    autoremove: true
    purge: true
