#!/bin/bash

CONFIGS_DIR=$(dirname $(readlink -f "."))/configs

print_help () {
  echo "Enter at least one argument: "
  echo "i : Install the configs"
  echo "r : Remove current configs"
}

print_green () {
  local green="\033[0;32m"
  local nc="\033[0m"
  echo -e "$green $1 $nc"
  echo -n -E ""
}

remove_configs() {
  print_green "[*] Cleaning configs"
  # vim
  rm "$HOME/.vim" -rf
  rm "$HOME/.vimrc"
  rm "$HOME/.config/nvim" -rf
  # emacs
  rm "$HOME/.emacs"
  rm "$HOME/.emacs.d" -rf
  # newsboat
  rm "$HOME/.newsboat" -rf
}

install_configs() {
  print_green "[*] Configuring"
  # vim
  mkdir "$HOME/.config/nvim/"
  for entry in "$CONFIGS_DIR/.config/nvim"/*; do
    ln "$entry" "$HOME/.config/nvim"
  done
  # emacs
  ln "$CONFIGS_DIR/.emacs" "$HOME/.emacs"
  # newsboat
  mkdir "$HOME/.newsboat"
  for entry in "$CONFIGS_DIR/.newsboat"/*; do
    ln "$entry" "$HOME/.newsboat"
  done
}

if [ -z "$@" ]; then
  print_help
else
  for arg in $@; do # loop over all arguments
    if [ $arg == "i" ]; then
      install_configs
    elif [ $arg == "r" ]; then
      remove_configs
    else
      print_green "[*] Wrong argument \" $arg \"!"
    fi
  done
fi
