# cheatsheet
# - to display unicode `tmux - u`
# - leader [ is copy mode vi

unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

# set terminal colors
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# creating panes
bind v split-window -h
bind s split-window -v

# bind sourcing
bind r source-file ~/.tmux.conf
set -g base-index 1

# disable multi command
set -g repeat-time 0

# vim-like pane switching
bind ^ last-window
bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

# vim copy pasting and nav
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# sessionizer
bind -r f run-shell "tmux neww ~/code/configs/tmux/tmux_sessionizer.sh"
